// Displays error message to user when there is an unexpected error


const UnhandledError = () => {
  return (
    <div className="wrap">
      <h2>Error</h2>
      <p>Sorry, there has been an unexpected error! </p>
    </div>
  );
};

export default UnhandledError;
